name             'starter'
maintainer       'Gustavo Garcia'
maintainer_email 'luctus@gmail.com'
license          'All rights reserved'
description      'Installs/Configures scheluder'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'mysql'
depends          'rbenv'
depends          'ruby_build'
depends          'ohai'
depends          'nginx'
